name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: checkout source code
      uses: actions/checkout@master
    - name: test file
      run: |
        $encoded = "${{ secrets.AUTH_FILE }}"
        [IO.File]::WriteAllBytes((Join-Path (Resolve-Path .\).Path "example.pfx"), [Convert]::FromBase64String($encoded))
#     - name: Install nsis software
#       run: choco install nsis
#     - name: Run nsis compiler
#       run: MakeNSIS example.nsi
    - name: Create release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_KEY }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      id: upload_asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_KEY }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./cert.pfx
        asset_name: cert.pfx
        asset_content_type: application/octet-stream
      
